import { StyleSheet } from 'react-native';
import { ColorsType } from 'src/theme/colors';

export const getStyles = (colors: ColorsType) =>
  StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: colors.background,
    },
    header: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingHorizontal: 16,
      paddingVertical: 12,
      borderBottomWidth: 1,
      borderBottomColor: colors.border,
      backgroundColor: colors.card,
    },
    headerLeft: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 12,
    },
    backButton: {
      padding: 4,
    },
    headerTitle: {
      fontSize: 18,
      fontWeight: 'bold',
      color: colors.text,
    },
    selectorSection: {
      paddingHorizontal: 16,
      paddingTop: 12,
      paddingBottom: 6,
      backgroundColor: colors.background,
    },
    selectorLabel: {
      fontSize: 12,
      marginBottom: 4,
      fontWeight: '500',
      color: colors.textSecondary,
    },
    modelSelectorWrapper: {
      width: '100%',
    },
    infoBar: {
      flexDirection: 'row',
      alignItems: 'center',
      marginHorizontal: 16,
      marginTop: 8,
      marginBottom: 8,
      paddingVertical: 8,
      paddingHorizontal: 12,
      borderRadius: 8,
      borderWidth: 1,
      backgroundColor: colors.card,
      borderColor: colors.border,
    },
    infoItem: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
    },
    infoText: {
      fontSize: 12,
      fontWeight: '500',
      color: colors.text,
    },
    infoDivider: {
      width: 1,
      height: 14,
      backgroundColor: '#88888844',
      marginHorizontal: 12,
    },
    chatList: {
      flex: 1,
      paddingHorizontal: 16,
    },
    chatListContent: {
      paddingVertical: 12,
      flexGrow: 1,
    },
    emptyContainer: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
      paddingHorizontal: 24,
      paddingVertical: 48,
    },
    emptyTitle: {
      fontSize: 16,
      fontWeight: 'bold',
      marginTop: 12,
      marginBottom: 6,
      color: colors.text,
    },
    emptyText: {
      fontSize: 13,
      textAlign: 'center',
      lineHeight: 18,
      color: colors.textSecondary,
    },
    userMessageBubble: {
      alignSelf: 'flex-end',
      maxWidth: '85%',
      backgroundColor: colors.primary,
      paddingHorizontal: 14,
      paddingVertical: 10,
      borderRadius: 16,
      borderBottomRightRadius: 4,
      marginBottom: 12,
    },
    userMessageText: {
      color: '#FFFFFF',
      fontSize: 14,
      lineHeight: 20,
    },
    responseCard: {
      alignSelf: 'flex-start',
      width: '100%',
      borderRadius: 14,
      borderWidth: 1,
      padding: 14,
      marginBottom: 14,
      backgroundColor: colors.card,
      borderColor: colors.border,
      elevation: 2,
      shadowColor: colors.shadown,
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.1,
      shadowRadius: 3,
    },
    cardHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      paddingBottom: 8,
      marginBottom: 10,
      borderBottomWidth: 1,
      borderBottomColor: colors.border,
    },
    cardHeaderLeft: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      flex: 1,
      marginRight: 8,
    },
    cardModelName: {
      fontSize: 12,
      fontWeight: '500',
      color: colors.textSecondary,
    },
    cardHeaderRight: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
    },
    cardTime: {
      fontSize: 11,
      color: colors.textSecondary,
    },
    copyIconBtn: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 4,
      paddingHorizontal: 8,
      paddingVertical: 4,
      borderRadius: 6,
      backgroundColor: colors.primary + '15',
    },
    copyBtnText: {
      fontSize: 11,
      fontWeight: '600',
      color: colors.primary,
    },
    responseText: {
      fontSize: 14,
      lineHeight: 22,
      color: colors.text,
    },
    clickHint: {
      fontSize: 11,
      marginTop: 10,
      fontStyle: 'italic',
      color: colors.textSecondary,
    },
    inputSection: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingHorizontal: 12,
      paddingVertical: 10,
      borderTopWidth: 1,
      borderTopColor: colors.border,
      backgroundColor: colors.card,
      gap: 8,
    },
    textInput: {
      flex: 1,
      minHeight: 40,
      maxHeight: 120,
      backgroundColor: colors.background,
      borderColor: colors.border,
      borderWidth: 1,
      borderRadius: 20,
      paddingHorizontal: 16,
      paddingVertical: 8,
      fontSize: 14,
      color: colors.text,
    },
    sendButton: {
      width: 42,
      height: 42,
      borderRadius: 21,
      backgroundColor: colors.primary,
      justifyContent: 'center',
      alignItems: 'center',
    },
    sendButtonDisabled: {
      opacity: 0.5,
    },
    // Windows Specific Modal Styles
    modalOverlay: {
      flex: 1,
      backgroundColor: 'rgba(0,0,0,0.6)',
      justifyContent: 'center',
      alignItems: 'center',
      padding: 24,
    },
    windowsPopupContent: {
      width: '90%',
      maxWidth: 800,
      height: '85%',
      borderRadius: 16,
      borderWidth: 1,
      borderColor: colors.border,
      backgroundColor: colors.background,
      overflow: 'hidden',
    },
  });
